### ISSUE TITLE
Unrecognized calling convention: 3

### ISSUE THREAD

**Issue by JoJpeg** [kritzikratzi/edsdk4j#38]
Hey there! I was using your library sucessfully in a project but now my hdd blew and i had to re setup my project files. Now i am getting the "java.lang.IllegalArgumentException: Unrecognized calling convention: 3" error from jna. 

i searched the whole web and tried to run the code with a 32bit jre, and tried different JNA versions and also tried to regenerate the JNA wrapper classes. i am not the moset versitile programmer, so did i miss something obvious?  

`java.lang.IllegalArgumentException: Unrecognized calling convention: 3
	at com.sun.jna.Function.checkCallingConvention(Function.java:217)
	at com.sun.jna.Function.<init>(Function.java:168)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:344)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:324)
	at com.sun.jna.Library$Handler.invoke(Library.java:203)
	at com.sun.proxy.$Proxy0.EdsInitializeSDK(Unknown Source)
	at edsdk.api.CanonCamera.dispatchMessages(CanonCamera.java:118)
	at edsdk.api.CanonCamera.access$000(CanonCamera.java:55)
	at edsdk.api.CanonCamera$1.run(CanonCamera.java:96)`

**Comment by kritzikratzi** [comment]
i can't fix this for you, but i would say you most likely have a 32/64 bit mismatch.
